### ISSUE TITLE
Integration with BakingSheet

### ISSUE THREAD

**Issue by mgmhunt** [CarterGames/NotionToUnity#1]
Hi - just exploring the idea of using Notion.

Not sure if you're aware of this project - https://github.com/cathei/BakingSheet

I'm using it to import Google Sheets to SO (also converting to Atom SO).

It looks very much like there is an overlap between functionalities here - BakingSheet has the capabilities to extend with various converters.

I was also interested in your limitations  - 100 rows for Database and in order of creation.

With the Filter and Sort here https://developers.notion.com/reference/post-database-query can you retrieve more than 100 via multiple requests? i.e. is the limitation a current issue of Notion API or just something that's not implemented yet in your system?

**Comment by JonathanMCarter** [comment]
Hi, yea I'm not surprised there are similar convertors to scriptable objects out there. I based this on a system at my current work which is similar using google sheets to unity with scriptable objects. I mainly made this as a personal tool, but shared in-case anyone found it useful. 

As for the 100 limit, I recently have updated it on my end to do just that. It now supports as large a database as needed with sorting options. Filters are a little harder to manage with fewer use-cases in my personal projects at this time, so I've not made that bit yet. Though I do plan to work that out sometime in the future. Not a priority at the moment though. 

The new version I've just not gotten around to publishing yet. I still want to tweak a few bits in the editor first, but have like 7 projects going at once and keep jumping between them. Procrastinating at its worst. Will get it out sometime this month hopefully xD

If the peeps running the other repo would like to use this as a base for their own converter they are more than welcome to. So long as it honors the licenses etc.

**Comment by mgmhunt** [comment]
Sweet will keep an eye on the repo then - thanks!
